### ISSUE TITLE
Cannot Build Latest Project

### ISSUE THREAD

**Issue by Narnian12** [FirelyTeam/Firely.Fhir.ValidationDemo#10]
**Describe the bug**
One of the NuGet dependencies in this project relies on a package that cannot be found. I presume it is the [private repo that might become public in January](https://github.com/FirelyTeam/firely-validator-api/issues/267), but am not sure.

**To Reproduce**
- Clone the project
- Two dependencies are in prerelease and not available

![image](https://github.com/FirelyTeam/Firely.Fhir.ValidationDemo/assets/9542535/a8831640-26d6-4fda-8b83-aa18534676ee)

FHIR Version: R4

**Comment by ewoutkramer** [comment]
Ah, that's right. We're publishing it this week!

**Comment by ewoutkramer** [comment]
You should be fine now!
