### ISSUE TITLE
Versioning libray

### ISSUE THREAD

**Issue by leonrenkema** [FirelyTeam/Firely.Fhir.ValidationDemo#2]
I'm experiencing the error as described here https://github.com/ewoutkramer/fhir-net-api/issues/481 and I was wondering if that should be fixed in the 1.4 release of the validationdemo. 

Maybe an idea to report that version/git commit somewhere when running the validation?

**Comment by ewoutkramer** [comment]
That's a good idea, surely would make my life easier as well ;-)
