### ISSUE TITLE
1.5.1 release is broken (can't find the core structuredefinitions)

### ISSUE THREAD

**Issue by vadi2** [FirelyTeam/Firely.Fhir.ValidationDemo#3]
The 1.5.1 release just says this when trying to validate a `Patient` that is OK under `1.4`: 

> [ERROR] Unable to resolve reference to profile 'http://hl7.org/fhir/StructureDefinition/Patient' (at Patient)

**Comment by ewoutkramer** [comment]
Interesting, I used it at DevDays....something fishy must be going on

**Comment by ewoutkramer** [comment]
Maybe I forgot to distribute the .zip with the definitions with it?

**Comment by vadi2** [comment]
Hm, no, `specification.zip` is there. Odd

**Comment by ewoutkramer** [comment]
It's weird, since Ardon recently reported bugs from the validator from inside a clearly functional validator tool 1.5.1.  Anyway, we'll see if we can reproduce it!

**Comment by ewoutkramer** [comment]
After this mega-update, everything should be fine again!
